### ISSUE TITLE
Intermittent import errors when starting remote scripts

### ISSUE THREAD

**Issue by Penumbra69** [danielyxie/bitburner#3888] opened 2022-07-04 20:16 UTC
A behavior that has been mildly annoying for a long time has been getting worse, so I thought I'd bring it up.

I, like many, start thousands of scripts all over the game to weak/grow/hack a target.
My hack/weak/grow script also have an import for some communications callback when the operation is complete.

Once in a while (one in 200k?) I receive a pop-up that I have to dismiss regarding dynamic imports.
Since I launch thousands of scripts / threads potentially a second, this is actually popping up a lot - and I'm wearing my ESC key out!

The below is a the result of script on home calling exec() to run a script on a purchased server -- pserv-16384G-16 to weaken hong-fang-tea -- the other args are mildly irrelevant (# of threads used, and a GUID to keep uniquity in each execution).

```
RUNTIME ERROR
/orobouros/weak.js@pserv-16384G-16 (PID - 206888)
Args: ["hong-fang-tea", 53, false, "808fe07e-84d5-4e52-aec3-d63caa6f8974"]

Failed to fetch dynamically imported module: blob:https://danielyxie.github.io/0ec81545-9a1e-4a1b-8144-9dab6ca1cc39
stack:
TypeError: Failed to fetch dynamically imported module: blob:https://danielyxie.github.io/0ec81545-9a1e-4a1b-8144-9dab6ca1cc39
```

I do not know how to read this error to determine what the root cause could be, but it has been growing in frequency.

I thought at first I was not waiting long enough after an `scp` of my hack scripts to the remote host to finish, so I added some sleep states to that as well as checking for a state file before execution with no help (though it did clear another error 'script does not contain a main{}'.

If there's some remedy I can introduce to my scripts to alleviate this, I'm all ears!
Can I disable this somewhere!?

 - P
 
[x] Version of the game: Bitburner v1.7.0 (b60f3da8)
Browser: [Version 1.38.119 Chromium: 101.0.4951.67 (Official Build) (x86_64)](https://brave.com/latest/)

**Comment by Snarling** [comment] 2022-07-06 20:58
Dynamic imports at runtime are not officially supported due to the way the game handles ram calculation. Is there a reason you need this import to be dynamic?

**Comment by hydroflame** [comment] 2022-07-21 19:35
Duplicate of that other scp issue

**Closed by hydroflame** 2022-07-21 19:35 UTC

**Comment by Penumbra69** [comment] 2022-07-22 17:45
I'm not actually using dynamic imports, this is just the error your game reports to me.
I have tried using dynamic imports, but hit the RAM calculation part and decided to spend my time elsewhere.

Here's what the script show above that intermittently fails looks like 'weak.js':
```js
import { makeNewMessage, sendLogMessage } from "/orobouros/comms.js"

/** @param {NS} ns **/
export async function main(ns) {
    // We HAVE to deliver these messages.. Restructuring..
    let res = await ns.weaken(ns.args[0])

    // If queue is full, we run again .. That's the deal - read the queue faster MCP....
    while (!await sendLogMessage(ns, makeNewMessage(ns, ns.getHostname(), ns.args[0], "WEAK_COMPLETE", res, "WEAK", ns.args[1])))
        res = await ns.weaken(ns.args[0])
}
```

I see a note from @hydroflame that this is a duplicate, though I did search for one.  
Can you link the item or # that this seems to be duplicating, as it was closed as "completed" with no links.

Thanks,
P
