### ISSUE TITLE
Bladeburner with negative contracts remaining

### ISSUE THREAD

**Issue by LunarPong** [danielyxie/bitburner#4022] opened 2022-08-22 17:31 UTC
Bitburner v2.0.2 (3067703c)
[bitburnerSave_1661188743_BN12x26.zip](https://github.com/danielyxie/bitburner/files/9396335/bitburnerSave_1661188743_BN12x26.zip)

I set a sleeve to perform bladeburner actions, take on contracts doing tracking actions. In the past it would stop once remaining contracts was 0. Once it hit zero it flipped to negative number and kept going.

**Comment by phyzical** [comment] 2022-08-23 01:20
may be related to https://github.com/danielyxie/bitburner/issues/3963

**Comment by MPJ-K** [comment] 2022-08-24 17:02
This is most likely unrelated to #3963. I tested this issue as well and confirmed that it exists for every type of contract (see image).  
I suspect that it is caused by the following:

In [SleeveBladeburnerWork.ts](https://github.com/danielyxie/bitburner/blob/dev/src/PersonObjects/Sleeve/Work/SleeveBladeburnerWork.ts), action count is never checked and it simply calls `completeAction()`. For the player, action count is checked in `startAction()`, but Sleeves completely bypass that check by going straight to `completeAction()`.

Hopefully this helps.

![BitburnerSleeveContractsBug](https://user-images.githubusercontent.com/104721042/186477035-2b5232fc-a3b8-43ba-ae08-e8d3d62522de.png)

**Closed** 2022-08-29 14:18 UTC
