### ISSUE TITLE
Nestet Import problem

### ISSUE THREAD

**Issue by Unikron** [danielyxie/bitburner#2408] opened 2022-01-06 18:48 UTC
Nestet Imports get not updated. My game is running under Windows,Steam. Is this a feature or a bug or I´m doing it wrong? Example:

run bug1.js
Changing bug3.js does nothing.
	Saveing bug1.js with changing content does nothing.
		Saveing bug2.js with out changing does nothing.
			Saveing bug2.js with changing content gives the new output.
Restarting the game gives the new output.

//Filename bug1.js
import { bug2 } from "bug2.js"
/** @param {NS} ns **/
export async function main(ns) {
	ns.tprint("bug1");
	await bug2(ns);
}

//Filename bug2.js
import {bug3} from "bug3.js"
/** @param {NS} ns **/
export async function bug2(ns) {
	ns.tprint("bug2");
	await bug3(ns);
}

//Filename bug3.js
/** @param {NS} ns **/
export async function bug3(ns){
	ns.tprint("bug3");//------Update this line to test
}

**Comment by macdjord** [comment] 2022-01-06 23:10
This is probably due to https://github.com/danielyxie/bitburner/issues/2413

**Comment by smolgumball** [comment] 2022-01-13 06:31
Dupe of #2336

**Closed** 2022-03-11 03:25 UTC
