### ISSUE TITLE
Can continue to train at a gym even after travelling to a different continent

### ISSUE THREAD

**Issue by JamesCarlyleClarke** [danielyxie/bitburner#2985] opened 2022-02-15 04:53 UTC
BitBurner V1.4.0 (49DE4A28)

Can continue to train at a gym even after travelling to a different continent.

1) Go to gym.
2) Train in a discipline
3) Choose 'Do something else simultaneously'
4) Choose Travel
5) Select a different city
6) Enjoy being in two continents at the same time.

This may well work for universities too, and any similar locations.

**Comment by phyzical** [comment] 2022-02-15 12:01
dupe of https://github.com/danielyxie/bitburner/issues/2740

**Closed** 2022-02-15 12:24 UTC
