### ISSUE TITLE
possible contract error

### ISSUE THREAD

**Issue by Ellastoman** [danielyxie/bitburner#3784] opened 2022-05-28 10:26 UTC
I am trying to solve a contract, 'Shortest Path in a Grid', and I can't find path through. I have been trying to put a [''] for an answer but it keeps telling me 'Contract Failed'.
contract-191027.cct
game version 1.7.0 (6b0f3da8)
# DELETE THIS AFTER READING

# include (where relevant)

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce
- [ ] Version of the game, e.g. Bitburner v1.3.0 (216bf616)
![shortest path in a grid - error](https://user-images.githubusercontent.com/106430762/170821311-528f017e-d8fe-4b78-a208-f9d9542008cc.png)

**Comment by phyzical** [comment] 2022-05-30 08:34
duplicate of #3755

**Closed** 2022-09-23 07:02 UTC
