### ISSUE TITLE
Edited files are not getting reloaded

### ISSUE THREAD

**Issue by poi2poi** [danielyxie/bitburner#2560] opened 2022-01-11 18:22 UTC
Hi there

My file structur is like this:
master.ns --> imports 'taskManager.ns'
taskManager.ns --> imports 'class_task.js'
class_task.js --> is class definiton, but same issues with any library

I have the issue that when I edit a class / library files, but I didn't edit the main / master file, the edited library file remains in it's old state, just like if I didn't save it. The scripts are not running when I try this. When I reload all scripts (aka reset the game), it will then work as supposed.

It seems like the files stay in a cache

I'm using the latest update 1.3 via Steam on Linux Mint 21 (or so)..

**Comment by smolgumball** [comment] 2022-01-13 06:06
Duplicate of #2336

**Closed** 2022-01-17 20:56 UTC
