### ISSUE TITLE
Running `kill` on a script that uses asleep to do something in parallel causes the "UNCAUGHT PROMISE ERROR" dialogue box to appear.

### ISSUE THREAD

**Issue by ballardrog** [danielyxie/bitburner#2425] opened 2022-01-07 11:12 UTC
Steps to reproduce:

1. Save the following as repro.js:
```javascript
/** @param {NS} ns **/
export async function main(ns) {
	delayedPrint(ns);
	await ns.asleep(10_000);
}

async function delayedPrint(ns) {
	await ns.asleep(5_000);
	ns.tprint("Foo");
}
```
2. run repro.js
3. kill repro.js (within 5 seconds)
4. The UNCAUGHT PROMISE ERROR dialog box appears 5 seconds after you ran repro.js.

Would it be possible to mark the environment of a killed process, so that the error only shows up for scripts that exited normally instead of also showing up for scripts that were killed?

Note that there is a workaround:
```javascript
/** @param {NS} ns **/
export async function main(ns) {
	delayedPrint(ns).then(() => { }, () => { });
	await ns.asleep(10_000);
}

async function delayedPrint(ns) {
	await ns.asleep(5_000);
	ns.tprint("Foo");
}
```

**Comment by heap-underflow** [comment] 2022-01-09 02:58
IMO, the bug is in the fact that your delayedPrint (an async function) doesn't _always_ throw the uncaught promise error when it's not awaited (or otherwise resolved) like you have, not that it only sometimes does (when killed).

You get the same error, with a slightly different `delayedPrint` function, ***even without killing*** the process.

```js
/** @param {NS} ns **/
export async function main(ns) {
	delayedPrint(ns)
	ns.asleep(10_000)
}

async function delayedPrint(ns) {
	ns.tprint(0)
	await ns.asleep(1_000)
	ns.tprint(1)
	await ns.asleep(1_000)
	ns.tprint(2)	
}
```

So, I don't think the issue is in how it's behaving when scripts are killed, I think the real issue (in a loose sense) is that you don't _always_ get the error when you're not resolving promises.

An alternative to your `/then` then might be
```js
await Promise.all([delayedPrint(ns), ns.asleep(10_000)])
```

**Comment by ballardrog** [comment] 2022-01-09 04:33
The modified version you gave is only throwing an error because the asleep in main isn't being awaited. The error happens when code in a promise tries to access ns after the script dies, which can happen either because main exits normally or the process is killed. There are valid usecases for not awaiting an asleep-based function; I don't think that should always be an error. (And I don't think there's a clean way to make it be, anyway.)

**Comment by phyzical** [comment] 2022-02-12 08:42
not sure if this helps or is even possible but can you use the workerscripts's `.env.stopFlag` ?

**Closed** 2022-10-19 18:15 UTC
Labels: contributor-friendly
