### ISSUE TITLE
TypeError: Cannot convert undefined or null to object (at "ScriptEditor")

### ISSUE THREAD

**Issue by ParzivalWolfram** [danielyxie/bitburner#3496] opened 2022-04-18 15:33 UTC
### How did this happen?

Please fill this information with details if relevant.

- [x] Save file
- [x] Minimal scripts to reproduce the issue
- [x] Steps to reproduce

After updating to v1.6.4 through Steam, I opened the script editor right after startup (I missed the script list button) and immediately got the following error. Submitting ticket as requested by the game. No scripts seemed to be the cause of the issue...?

### Environment

* Error: TypeError: Cannot convert undefined or null to object
* Page: ScriptEditor
* Version: v1.6.4 (d5b296dd)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.6.4 Chrome/93.0.4577.82 Electron/14.2.4 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
[RECOVERY_BITBURNER_1650295509.json.zip](https://github.com/danielyxie/bitburner/files/8506583/RECOVERY_BITBURNER_1650295509.json.zip)

**Comment by dowinter** [comment] 2022-04-18 15:58
Had the same thing happen after opening script editor for the first time, guess there is something stale there.

**Comment by dowinter** [comment] 2022-04-18 16:10
Also: Soft resetting the game after the crash and opening the Editor again doesn't crash now (at least not immediately)

**Comment by dowinter** [comment] 2022-04-18 16:11
Possibly duplicate of #3496

**Comment by ParzivalWolfram** [comment] 2022-04-18 16:39
I just continued in recovery mode and all was well, so it seems to be an
issue that only happens once?

**Closed** 2022-04-18 16:49 UTC
