### ISSUE TITLE
TypeError: Cannot convert undefined or null to object (at "ScriptEditor")

### ISSUE THREAD

**Issue by ToxicSamurai** [danielyxie/bitburner#3497] opened 2022-04-18 15:37 UTC
### How did this happen?

Please fill this information with details if relevant.

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce

### Environment

* Error: TypeError: Cannot convert undefined or null to object
* Page: ScriptEditor
* Version: v1.6.4 (d5b296dd)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.6.4 Chrome/93.0.4577.82 Electron/14.2.4 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
```

**Comment by ToxicSamurai** [comment] 2022-04-18 15:44
Save won't upload

```var n00dles = args[0];
var moneyThresh = getServerMaxMoney('n00dles') * 0.75;
var securityThresh = getServerMinSecurityLevel('n00dles') + 5;

while(true) {
    if (getServerSecurityLevel('n00dles') > securityThresh) {
        weaken('n00dles');
    } else if (getServerMoneyAvailable('n00dles') < moneyThresh) {
        grow('n00dles');
    } else {
        hack('n00dles');
    }
}```

Installed augmentations, opened n00dles.script using nano, entered recovery mode

**Comment by dowinter** [comment] 2022-04-18 16:12
Possibly duplicate of #3496

**Closed** 2022-04-18 16:49 UTC
