### ISSUE TITLE
BN4 - Cant work for Nitesec

### ISSUE THREAD

**Issue by xdamageincx** [danielyxie/bitburner#2922] opened 2022-02-05 14:01 UTC
/** @param {NS} ns **/
export async function main(ns) {
	ns.workForFaction("NiteSec", "Hacking Contracts", false);
}

Am a member of nitesec and this returns false.  Work does not proceed.  Am not currently busy.  There seem to be other instances of this same issue presented on the discord outside of the bug-report channel but i did not see it in the Bug Reports (might have missed).

To add to this, I THINK my script successfully worked for them over night as i have ~3k faction rep.  It seems it stopped being able to work for them at some point and now the test code above doesnt even work.   I CAN manually work for them though.

After working on this I think I understand what is happening.  After joining a gang you can still be member of a faction that has a gang until next aug reset.  You can still interact with that gang normally manually, but the singularity script disallows work for a faction of an opposing gang.

**Comment by phyzical** [comment] 2022-02-12 15:19
`but the singularity script disallows work for a faction of an opposing gang.` this is by design

closable

**Comment by mfortner** [comment] 2022-02-12 19:52
> `but the singularity script disallows work for a faction of an opposing gang.` this is by design
> 
> closable

If it's by design, the UI should prevent you from working from the faction, too, not just the Singularity function.

**Comment by phyzical** [comment] 2022-02-13 01:26
when you join a gang you cant right? rather i thought you couldnt join any other factions?

ah maybe i jumped the gun on this one being closable.

is it more once you join a gang and you have already joined other factions? 

if so yeah sounds like singularity *may*  need a check for if they have completed BN2?

**Comment by xdamageincx** [comment] 2022-02-13 02:02
I believe the situation is as follows:

If you join a gang and are already a member of a rival faction,  you
maintain the membership in the UI. You can interact with them through UI,
but not singularity code.  I figured you should either be able to do both
or neither

**Comment by phyzical** [comment] 2022-02-13 02:13
yeah okay, ill have a sniff of the source and see if i can infer what should happen.

if i was to guess it would be probably the following

* joining a gang should work like BN2 (outside BN2), i.e the gang you join has all augmentations and all other factions are forced to be left

**Comment by TheMas3212** [comment] 2022-04-14 16:17
closed by #3454

**Closed** 2022-04-14 16:16 UTC
