### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name') (at "Work")

### ISSUE THREAD

**Issue by hi117** [danielyxie/bitburner#3008] opened 2022-02-20 23:55 UTC
### How did this happen?

IDK, wasn't doing anything special as far as I know. The script I ran was `/bootstrap2.js`.

Please fill this information with details if relevant.

- [x] Save file
- [ ] Minimal scripts to reproduce the issue
- [x] Steps to reproduce

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'name')
* Page: Work
* Version: v1.4.0 (49de4a28)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.0.0 Chrome/93.0.4577.82 Electron/14.0.2 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
Attached
[RECOVERY_BITBURNER_1645400015.json.zip](https://github.com/danielyxie/bitburner/files/8105204/RECOVERY_BITBURNER_1645400015.json.zip)

**Comment by hi117** [comment] 2022-02-20 23:59
Actually, I think it might be related to my work for faction script interacting with a script that calls installAugmentations

**Comment by pd** [comment] 2022-02-22 00:22
> Actually, I think it might be related to my work for faction script interacting with a script that calls installAugmentations

Yep, the `work for faction` screen being up when `installAugmentations`. Easy workaround for now is `setFocus(false)` prior to installing.

Dupe of #2902.

**Closed** 2022-03-11 02:41 UTC
