### ISSUE TITLE
Chained imports have caching issues

### ISSUE THREAD

**Issue by paulcdejean** [danielyxie/bitburner#2413] opened 2022-01-06 23:02 UTC
Demonstration:

https://www.youtube.com/watch?v=f9ImEGi__cs

https://discord.com/channels/415207508303544321/415213413745164318/928546119246565386

> When C.js is updated, C's hash is updated. (https://github.com/danielyxie/bitburner/blob/4860d6dc837189c4334cb0ceb7e0d8651b568aa9/src/Script/Script.ts#L125) The contents of B.js don't change, so B's hash doesn't get updated. When A.js imports B.js, because B's hash is the same, it loads the old compiled version of B.js, which was using the old version of C.js. (https://github.com/danielyxie/bitburner/blob/4860d6dc837189c4334cb0ceb7e0d8651b568aa9/src/NetscriptJSEvaluator.ts#L143)

**Comment by paulcdejean** [comment] 2022-01-06 23:03
Workaround: https://discord.com/channels/415207508303544321/415213413745164318/928560320052596826

> It seems like you can disable to import cache check by editing the main bundle ( <steam or wherever>\Bitburner\resources\app\main.bundle.js) and replacing
`l||(l=_getScriptUrls(s,t,a))`

with
`(l=_getScriptUrls(s,t,a))`

For me, Sublime tells me it was Line 19, Column 84050

**Comment by smolgumball** [comment] 2022-01-13 06:31
Dupe of #2336

**Closed** 2022-01-17 20:56 UTC
