### ISSUE TITLE
CorporationAPI - assignJob very slow

### ISSUE THREAD

**Issue by ThatGuyinIT** [danielyxie/bitburner#2997] opened 2022-02-17 14:52 UTC
When using ns.corporation.assignJob() in a script, it is very slow - far slower than simply clicking through the Corp UI. It feels like a defect.

> 
    let office = ns.corporation.getOffice(division.name, city);
    for (const employee of office.employees) {
        let job = getNextJob(office.size, emp_num, researchDone);
        await ns.corporation.assignJob(division.name, office.loc, employee, job); // << THIS
        emp_num++;
    }

**Comment by daiwai** [comment] 2022-02-17 20:34
Looks like this is intentional: https://github.com/danielyxie/bitburner/blob/13453e678fefeff809c8a117276b3a0bc10235d6/src/NetscriptFunctions/Corporation.ts#L550

Maybe in order to prevent dynamically switching emloyees between positions for the production and selling periods during a corporation cycle?

**Comment by phyzical** [comment] 2022-02-18 10:30
@pigalot do you remember why? was it just a balancing thing? or maybe what @daiwai has mentioned

**Comment by pigalot** [comment] 2022-02-18 13:11
The 1 second is intentional Its copied from the original assign.

**Comment by phyzical** [comment] 2022-02-19 01:39
@ThatGuyinIT a workaround is to have it running in a separate script but that is another 1tb ram (but i assume by the point your at this many employyees you should have enough money to buy more home ram)

**Comment by ThatGuyinIT** [comment] 2022-02-19 19:13
@phyzical Yes, though to make it in any way efficient, that I would want 6 scripts running in parallel (and thus 6TB), which would still only bring it down to 10 minutes to complete.

**Comment by phyzical** [comment] 2022-02-20 03:26
is there a reason you need to reassign so many employees? wouldn't it just be a gradual increase in all positions?

**Comment by ThatGuyinIT** [comment] 2022-02-21 08:24
@phyzical it is just ease of code - it is just easier to reassign based on percentages, e.g. first 40% are Ops, next 20% Engs etc, rather than each time count how many are in the existing role and do the delta each time, e.g. an office maxes out Research or adds 30 new hires.

It means that each time, you just run through the full list of employees again. The 1 second delay just means that a lot more logic has to be wrapped around this one single action than feels necessary.

**Comment by phyzical** [comment] 2022-02-21 09:54
why not just ask to assign those values? you shouldn't need to reassign.

i.e say you have 100 employees 40% would be 40, then next time say there is 200 emplyees, then 40% is 80 just provide 40 then 80 and it will just asign another 40 instead of unassigning 40 then reassigning 80

**Comment by ThatGuyinIT** [comment] 2022-02-21 12:54
I added some logic to not reassign employees to the same jobs they already have, that saves the majority of the time. 

I just don't want to spend too much time worrying about this aspect of the bitnode when the whole Corp has so many other moving pieces that have to be considered, e.g. divisions, offices, products, corp upgrades, division research, etc.

**Comment by phyzical** [comment] 2022-02-21 12:57
i understand, there is other prs that has been confirmed to speed things up. im just giving you some suggested workaround for now, so there is not ETA when these will make in into prod

**Comment by pigalot** [comment] 2022-02-21 14:05
Frankly most people don't bother with multiple working divisions so its not a problem for them, I think any change to this would go with a more robust change to the corp mechanic that would make using multiple corps more viable.

**Comment by phyzical** [comment] 2022-02-22 02:09
agreed, there is alot of loop all x -> y > z that is repeated that could be refactored/consolidated

**Comment by hydroflame** [comment] 2022-02-23 07:12
This is intended, otherwise players can just assign their employee every corporation cycle and cheat the system.

**Closed by hydroflame** 2022-02-23 07:12 UTC
