### ISSUE TITLE
Files with same name get highlighted

### ISSUE THREAD

**Issue by Leorias** [danielyxie/bitburner#2401] opened 2022-01-06 15:59 UTC
All Files with the same name get highlighted instead of just the currently opened one.

![image](https://user-images.githubusercontent.com/84665910/148411676-04ba1e0f-b3c8-4dbc-8592-22bbfb59a338.png)

**Comment by Rasmoh** [comment] 2022-09-08 22:42
This is a dupe of #2958 which was fixed by #2989.

**Closed** 2022-09-23 06:50 UTC
Labels: contributor-friendly
