### ISSUE TITLE
Bad error message for setToCommitCrime() with incorrect sleeve index

### ISSUE THREAD

**Issue by apricotorange** [danielyxie/bitburner#2522] opened 2022-01-09 21:42 UTC
For example:

```
export async function main(ns) {
  ns.sleeve.setToCommitCrime(NaN, "Homicide");
}
```

```
RUNTIME ERROR
experiment.js@home

e.sleeves[i] is undefined
stack:
setToCommitCrime@https://danielyxie.github.io/bitburner/main.bundle.js:19:267885
main@blob:https://danielyxie.github.io/87c5d1a4-8b83-4bd7-b5cc-eed058f9cc20:141:13
executeJSScript@https://danielyxie.github.io/bitburner/main.bundle.js:19:83439
```

Similar issue for `ns.sleeve.setToCommitCrime(0.5, "Homicide");`

**Comment by deathly809** [comment] 2022-01-12 06:17
The problem is because NaN has a type "number", whoops!  Going to kick off a new PR

```ts
    number: (funcName: string, argName: string, v: any): number => {
      if (typeof v === "number") return v;
      if (!isNaN(v) && !isNaN(parseFloat(v))) return parseFloat(v);
      throw makeRuntimeErrorMsg(funcName, `${argName} should be a number`);
    },
```

**Comment by deathly809** [comment] 2022-01-12 16:31
PR merged!  Not sure when an update will be rolled out, but should be fixed!

**Closed** 2022-03-11 03:22 UTC
Labels: contributor-friendly
