### ISSUE TITLE
Changes in transitive script dependencies not detected until game reload

### ISSUE THREAD

**Issue by macgregor** [danielyxie/bitburner#2443] opened 2022-01-07 21:03 UTC
# Problem 
Code changes to nested transitive dependencies in scripts are not detected, forcing you to reload the game for them to be picked up.

# Context
I have a number of library modules that export functions/classes, with a single library file which aggregates them together to be used as an import. E.g. "lib_foo.js" and "lib_bar.js" which contain shared code, and "lib.js" which simply re-exports those files (`export * from "lib_foo.js"`) and is used as a single import in executable scripts (`import * from "lib.js"` gives you everything "lib_foo.js" and "lib_bar.js" export).

# Steps to reproduce

1. Create 3 files:

**transitive_dependency.js**
```
export function transitive_fn(ns){
	ns.tprint("foo")
}
```

**dependency.js**
```
export * from "transitive_dependency.js"
```

**bug.js**
```
import * as lib from "dependency.js"

export async function main(ns) {
	lib.transitive_fn(ns)
}
```

2. Run "bug.js" and see expected output: "foo"
3. Modify "transitive_dependency.js" to print a different string, e.g. `ns.tprint("bar")`
4. Run "bug.js" and see the old output ("foo") rather than the expected updated value ("bar")
4. Reload the game
5. Run "bug.js", see expected output: "bar"

Alternatively, modifying the directly imported dependency ("dependency.js") also causes the changes in the transitive dependency to be detected.

**Comment by heap-underflow** [comment] 2022-01-09 01:33
Dupe of #2413

**Comment by smolgumball** [comment] 2022-01-13 06:31
Dupe of #2336

**Closed** 2022-03-11 03:25 UTC
