### ISSUE TITLE
Create Programs page not appearing

### ISSUE THREAD

**Issue by Papayaman1000** [danielyxie/bitburner#632] opened 2019-06-18 17:22 UTC
While there are programs able to be created, and the page itself is accessible via the keyboard shortcut, the actual menu item never actually appeared for me. It just... doesn't exist.
![image](https://user-images.githubusercontent.com/24946071/59705292-1862e100-91cc-11e9-9d7c-02c13d6cf57f.png)
[Firefox 67.0.2 on Windows 10]

**Comment by Papayaman1000** [comment] 2019-06-21 16:28
Quick Update: So  I had restarted Firefox at some point and the menu item appeared.

**Comment by danielyxie** [comment] 2019-07-16 04:42
Could not reproduce, but hopefully fixed in v0.47.2

**Closed by danielyxie** 2019-07-16 04:42 UTC
