### ISSUE TITLE
Stanek API + memory calculator make Map.get into unexpectedly expensive  function

### ISSUE THREAD

**Issue by Maykeye** [danielyxie/bitburner#2614] opened 2022-01-13 19:39 UTC
Problem:
Memory calculator thinks that Map.get is stanek.get and happily adds 2GB to ram requirement

Step to reproduce:
```
/** @param {NS} ns **/
export async function main(ns) {
	let z =  Map()
	z.get("wut")
}

[home ~/]> mem wut.js 

This script requires 3.60GB of RAM to run for 1 thread(s)
  2.00GB | stanek.get (fn)
  1.60GB | baseCost (misc)
```
Expected: just base cost, no  `  2.00GB | stanek.get (fn)`

What makes it worse - 2 GB is not  a small change to ignore at early game: using any code with [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)s on 4GB n00dles is practically out of question.

**Comment by heap-underflow** [comment] 2022-01-14 00:27
Dupe of #2529

**Closed** 2022-01-14 03:35 UTC
