### ISSUE TITLE
Recovery Mode - Triggered after script ran with argument `NaN`

### ISSUE THREAD

**Issue by miliarch** [danielyxie/bitburner#2033] opened 2021-12-19 06:45 UTC
Sadly I don't know what exactly happened. I was running scheduler.js around the time it happened - doing work in generateUniqueProcessArgs function. I noticed in ps output that a worker_grow.js script was launched with `NaN` as an argument, tried to kill it (it wouldn't die), then reloaded. On reload, I got the recovery notification.

[RECOVERY.json.zip](https://github.com/danielyxie/bitburner/files/7740419/RECOVERY.json.zip)

Hopefully this report is helpful.

**Comment by madisjanno** [comment] 2021-12-24 12:21
Also ran into this issue.

Can be easily recreated with this script (test.js) for example:

`/** @param {NS} ns **/
export async function main(ns) {
    if (!ns.args[0])
		ns.exec("test.js", "home", 1, NaN);
}`

**Comment by dwRchyngqxs** [comment] 2021-12-26 20:18
Same issue here, I ended up executing a script with NaN as an argument (from a NS1 script by going out of bounds on an array) and now there is a "ghost" script running on n00dles and there is no way to kill it. Here is my save
[RECOVERY.zip](https://github.com/danielyxie/bitburner/files/7777522/RECOVERY.zip).

**Comment by dwRchyngqxs** [comment] 2021-12-26 20:50
After diving into the code it seems like this issue is caused at the script removal from the server even if using killall:
[The script removal is done by value of the arguments](https://github.com/danielyxie/bitburner/blob/d99b03d12e19df4feb332976236b02a2fe51d22c/src/Netscript/killWorkerScript.ts#L104) even if killall does it by pid. So `NaN` not being equal to itself makes it fail. If there is a way to perform this step by pid it could solve the issue.

**Comment by ehguo** [comment] 2022-01-02 17:03
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is

There's this, although I haven't looked at the source code so not sure if NaN comparison is the real issue.

**Comment by dwRchyngqxs** [comment] 2022-01-04 13:35
`Object.is` [is not what is used currently](https://github.com/danielyxie/bitburner/blob/d99b03d12e19df4feb332976236b02a2fe51d22c/src/utils/helpers/compareArrays.ts#L23). Using it instead of `!==` (or rather using `!x.is(y)`) could solve the issue without having to do any other change. Though I won't be able to do it myself.
`NaN` comparison is definitely part of the issue, a process can't be matched to itself because of it. The way I proposed is not the only way to solve the issue, I think disallowing `NaN` as an argument is better.

Here is a way to reliably reproduce the bug:
1. Make a script calling `run` on any script not exceeding current free ram with `0/0` as an argument and run it.
1.1. (optional) Run `ps`, the script run with `NaN` should still be listed even if it should have finished running.
2. Save the game, you can do it without any risk for your save because the `Force kill all active scripts` button will kill all the script wih `NaN` as argument.
3. Reload the game, you should land on the Recovery page.

**Comment by dwRchyngqxs** [comment] 2022-01-26 11:43
It should be fixed now. Can you (@miliarch and @madisjanno) check if you still run into this issue using the dev branch?

**Comment by phyzical** [comment] 2022-02-07 14:34
i just tried to replicate your provided script nothing happens so i would say yes closable 👍

**Closed** 2022-03-11 03:27 UTC
Labels: contributor-friendly
