### ISSUE TITLE
bladeburner.setActionLevel does not throw an error when an invalid level is passed and allows any level to be set

### ISSUE THREAD

**Issue by MPJ-K** [danielyxie/bitburner#3963] opened 2022-08-07 13:15 UTC
The title pretty much says it all. Game version is v1.7.0 (cfcdc254). EDIT: Issue still exists in v2.0.2 (`3067703c`).
The `bladeburner.setActionLevel()` function will allow any level to be set, even if it is above the maximum level. This allows the player to cheat in bladeburner, because actions will work at the set level. I have not tried setting negative levels, because I fear it will break the game.

I do not sufficiently understand the source code to suggest an exact fix. However, I did notice that in [this](https://github.com/danielyxie/bitburner/blob/326d9fd7ef4042fb8fc031e6a94eeef091c98521/src/NetscriptFunctions/Bladeburner.ts#L253) file, (line 253) `ctx.helper.MakeRuntimeErrorMsg()` is used, while every other call to this function uses `ctx.MakeRuntimeErrorMsg()`. Perhaps that is where the problem lies.

**Comment by phyzical** [comment] 2022-08-09 08:08
hmm looking at the source it should be enforcing the maxlevel
```
const action = getBladeburnerActionObject("setActionLevel", type, name);
      if (level < 1 || level > action.maxLevel) {
        throw helper.makeRuntimeErrorMsg(
          "bladeburner.setActionLevel",
          `Level must be between 1 and ${action.maxLevel}, is ${level}`,
        );
      }
      action.level = level;
  ```

**Comment by MPJ-K** [comment] 2022-08-09 09:27
Not sure what file that is from, but I was looking in [bitburner/src/NetscriptFunctions/Bladeburner.ts](https://github.com/danielyxie/bitburner/blob/326d9fd7ef4042fb8fc031e6a94eeef091c98521/src/NetscriptFunctions/Bladeburner.ts#L253). Like I mentioned before, every call to `makeRuntimeErrorMsg()` in that file uses the `ctx.` prefix, while for `setActionLevel()` the prefix is `ctx.helper.`. Maybe the "`.helper`" needs to be removed.

I also tried validating my game files and the problem did not go away.

**Comment by MPJ-K** [comment] 2022-08-11 18:24
I am doing Bladeburner again so I took this image showing an action's level exceeding the maximum after running `ns.bladeburner.setActionLevel("Contract", "Tracking", 20);`.

![BitburnerSetActionLevelBug](https://user-images.githubusercontent.com/104721042/184211147-a974f6c3-a3be-4e94-ba9d-03ba27d84e4e.png)

**Comment by phyzical** [comment] 2022-08-12 02:00
@MPJ-K hmm yeah its clearly not working as intended thanks for the image confirmation.

the code above is where you have linked.   `const level = ctx.helper.number("level", _level);` all this will do is convert strings or whatever to a number, i guess its possible something has gone wrong but even if it was a string still js would handle that correctly

 so all i can think is that the object itself is not holding the correct "maxLevel" to what is seen in the ui 🤔

**Comment by MPJ-K** [comment] 2022-08-12 10:55
@phyzical I tested the action object in-game using a small test script:
```
ns.tprint(ns.bladeburner.getActionMaxLevel("Contract", "Tracking"));
ns.bladeburner.setActionLevel("Contract", "Tracking", 20);
ns.tprint(ns.bladeburner.getActionMaxLevel("Contract", "Tracking"));
```
The maxLevel is correctly returned both before and after setting the invalid level.

What I find curious is that in the code block you commented earlier there is a `throw` before the error, while there is no `throw` in the file I linked. If the error was not being thrown that would explain why maxLevel is correct and invalid levels can be set. I also tested setting the level to -100, which works (see image). This further confirms that maxLevel is not the problem.

![BitburnerSetActionLevelBug2](https://user-images.githubusercontent.com/104721042/184340204-2e1772d4-6f3f-49f6-8546-dd287a004fd4.png)

**Comment by phyzical** [comment] 2022-08-14 04:18
Ah! good spot, well that just means its fixed in 2.0 already :)

**Comment by MPJ-K** [comment] 2022-08-17 13:24
@phyzical I just tested the issue again in v2.0.1 (69934257) and it has NOT been fixed. Perhaps the fix is in an unmerged branch?

**Comment by phyzical** [comment] 2022-08-18 01:13
hmmmm ill give it a test myself tonight 👍

**Closed** 2022-08-29 14:20 UTC
