### ISSUE TITLE
EXCEPTION: Bladeburner.process()

### ISSUE THREAD

**Issue by Vic1970** [danielyxie/bitburner#3701] opened 2022-05-22 01:39 UTC
Bitburner 1.7.0 (b71418b0)

Had an exception thrown (screenshot attached) upon completion of the first bladeburner black op.

![bladeburner_exception ](https://user-images.githubusercontent.com/12029663/169674610-92acecac-9ed3-41c6-ad5c-671e2da93f4e.png)
[bitburnerSave_1653090265_BN10x1.zip](https://github.com/danielyxie/bitburner/files/8748605/bitburnerSave_1653090265_BN10x1.zip)

**Comment by xRalic** [comment] 2022-05-22 01:46
possible duplicate of #3685

**Comment by borisflagell** [comment] 2022-05-22 01:49
Absolutely a duplicate.

**Closed** 2022-05-23 00:37 UTC
