### ISSUE TITLE
Hacknet: Upgrade purchase functions need value for n after refactoring to `unknown`

### ISSUE THREAD

**Issue by dowinter** [danielyxie/bitburner#3168] opened 2022-03-18 08:54 UTC
Hey!

In https://github.com/danielyxie/bitburner/commit/28bd5e1b308b39febf2505d949192d4ed6a75881 several function arguments have been converted to `unknown` and then evaluated via `helper.number`. 
This unfortunately has the side effect, that functions like `hacknet.upgradeLevel` can not be called without `n` anymore: https://github.com/danielyxie/bitburner/blob/dev/src/NetscriptFunctions/Hacknet.ts#L94 
Previously, `upgradeLevel` resulted in a call to `purchaseLevelUpgrade`, which in case set `n` to a default value of `1` (https://github.com/danielyxie/bitburner/blob/bfa30dcdbb6e970cfe3e0b35b73542592d572df2/src/Hacknet/HacknetHelpers.tsx#L244), which signals to me that the default behaviour (calling upgrades without `n`) was intended, but is now blocked by the helper: https://github.com/danielyxie/bitburner/blob/88df76a868cb523433a77be549bc2f7a935ec3d1/src/NetscriptFunctions.ts#L441

Could someone clarify if this is indeed a problem? In that case I'd start to work on the issue today :)

**Comment by Master-Guy** [comment] 2022-03-18 09:03
@hydroflame can you comment on this?

**Comment by phyzical** [comment] 2022-03-18 09:12
@dowinter i know it might be annoying, but simply adding 1 should do the job right?

i guess we might need to be a bit more careful about what a "breaking change" is going forward

**Comment by dowinter** [comment] 2022-03-18 09:24
> @dowinter i know it might be annoying, but simply adding 1 should do the job right?
> 
> i guess we might need to be a bit more careful about what a "breaking change" is going forward

Yes the fix is easy, but either way the default paramaters for `purchaseLevelUpgrade` & co. would still be inconsistent.
That's why I asked what the intention was :)

**Comment by hydroflame** [comment] 2022-03-18 14:59
It's a bug, the default shoudl be 1, tis' an easy fix though

**Comment by hydroflame** [comment] 2022-03-18 15:20
Re-opening because the issue is fixed on web but Steamworks is down so I can't deploy it.

**Closed** 2022-03-18 15:33 UTC
