### ISSUE TITLE
Alert is not disappearing after clicking "Hire Employee" at Corp menu

### ISSUE THREAD

**Issue by IsseiKanda** [danielyxie/bitburner#3113] opened 2022-03-11 15:23 UTC
- version: 1.5.0(ca19e151)
- Steps to reproduce: Click "Hire Employee" Button at Corp menu more than twice.

The alert "Automatically hires an employee and gives him/her a random name" won't go away unless screen is switched to another menu.

**Comment by ChrissiQ** [comment] 2022-03-17 16:44
Duplicate of #3094

**Closed** 2022-03-19 15:39 UTC
